// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAml40K7lXHM22UuNqebm99cyIhbB8mT9g',
    appId: '1:34186473939:web:eebf3cf6f4c40feda13f26',
    messagingSenderId: '34186473939',
    projectId: 'testcli-b9b9f',
    authDomain: 'testcli-b9b9f.firebaseapp.com',
    storageBucket: 'testcli-b9b9f.appspot.com',
    measurementId: 'G-PGBGHZR89X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTP8-4MgcjhaceATnyN3qX5vk5cI-t-U',
    appId: '1:34186473939:android:0b8bad1c469ef6efa13f26',
    messagingSenderId: '34186473939',
    projectId: 'testcli-b9b9f',
    storageBucket: 'testcli-b9b9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_2A3LgpxRLBhfhLUZu_yNmyrFmRzUSlo',
    appId: '1:34186473939:ios:c762a45412405f8ea13f26',
    messagingSenderId: '34186473939',
    projectId: 'testcli-b9b9f',
    storageBucket: 'testcli-b9b9f.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_2A3LgpxRLBhfhLUZu_yNmyrFmRzUSlo',
    appId: '1:34186473939:ios:c762a45412405f8ea13f26',
    messagingSenderId: '34186473939',
    projectId: 'testcli-b9b9f',
    storageBucket: 'testcli-b9b9f.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAml40K7lXHM22UuNqebm99cyIhbB8mT9g',
    appId: '1:34186473939:web:727d33195e227532a13f26',
    messagingSenderId: '34186473939',
    projectId: 'testcli-b9b9f',
    authDomain: 'testcli-b9b9f.firebaseapp.com',
    storageBucket: 'testcli-b9b9f.appspot.com',
    measurementId: 'G-5ELNPRL3CD',
  );
}
